name: Publish

on:
  release:
    types: [created]

jobs:
  pypi:
    name: Release on PyPi.org
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install wheel
        pip install .
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  docs:
    name: Build docs for Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Pip
        run: |
          pip install -e .
          pip install pdoc
      - name: Pdoc
        run:  pdoc --footer-text='Version ${{ github.ref_name }}' bicpl -o pdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: pdoc
